name: titanic_env 
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - dagshub
      - numpy
      - pandas 
      - scikit-learn>=1.2 
      - xgboost 
      - mlflow 
      - joblib