name: TitanicSurvival

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: titanic_env
        environment-file: MLProject/conda.yaml
        auto-activate-base: false

    - name: Install pip dependencies
      run: |
        pip install mlflow dagshub joblib scikit-learn pandas numpy

    - name: Set Environment Variables
      env:
        MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
      run: |
        echo "Username and password loaded."

    - name: Run MLflow Project
      working-directory: MLProject
      env:
        MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
      run: |
        mlflow run . -P data_path=preprocessing/cleaned_data.csv --env-manager=local

    - name: Upload trained model
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: MLProject/models/forest_model.pkl

    - name: Upload MLflow logs
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-logs
        path: MLProject/mlruns/

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/titanic-mlproject:latest MLProject/

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/titanic-mlproject:latest
