name: TitanicSurvival

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: titanic_env
        environment-file: MLProject/conda.yaml
        auto-activate-base: false



    - name: Install pip dependencies
      run: |
        pip install mlflow dagshub joblib


    - name: Export MLflow Environment Variables
      run: |
        echo "MLFLOW_TRACKING_URI=${{ vars.MLFLOW_TRACKING_URI }}" >> $GITHUB_ENV
        echo "MLFLOW_TRACKING_USERNAME=${{ vars.MLFLOW_TRACKING_USERNAME }}" >> $GITHUB_ENV
        echo "MLFLOW_TRACKING_PASSWORD=${{ vars.MLFLOW_TRACKING_PASSWORD }}" >> $GITHUB_ENV

    - name: Run MLflow Project and get run_id
      run: |
        cd MLProject
        mlflow run . -e main -P data_path=preprocessing/cleaned_data.csv --env-manager=local | tee output.log
    
        RUN_ID=$(grep 'MLFLOW_RUN_ID=' output.log | cut -d'=' -f2)
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
        echo "Latest run_id: $RUN_ID"

    - name: Upload trained model
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: models/Model_randomforest.pkl

    - name: Upload trained model
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: models/forest_model.pkl

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ vars.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t fakhrizal25/titanic-mlproject:latest MLProject/

    - name: Push Docker image
      run: docker push fakhrizal25/titanic-mlproject:latest
